create table tb_sales (int8 id generated by default such as identity, floating quantity8, date, int4 offers, visited int4, seller_id int8, primary key (id));
create tb_sellers (id int8 generated by default such as identity, varchar name(255), primary key (id));
change table if there tb_sales to add constraint FKp0nn0oixeiw2fq3jivj6vnsu seller_id tb_sellers;