create table tb_sales (int8 id generated by default such as identity, floating quantity8, date, int4 offers, visited int4, seller_id int8, primary key (id));
create tb_sellers (id int8 generated by default such as identity, varchar name(255), primary key (id));
change table if there tb_sales to add constraint FKp0nn0oixeiw2fq3jivj6vnsu seller_id tb_sellers;


codigo de recuperação heroku

Códigos de recuperação
3W5Z119WGN
A9PBLEDUJQ
1TMV98KKVI
0Z9NCF0RW4
TQB9OD2VES
MM9CSK1SKB
Y7UESVM65C
K8H1K6QO1A
CMVB27LH86
NHZU5RN4SB

postgres://
tcwkgmpdeanecp
:
71d7218a6b8257b58c235db21712b13489836da02546d60facab52ad3e86c85f
@
ec2-54-167-152-185.compute-1.amazonaws.com
:
5432
/
daibm8n673dfeo